"""Install a small `quicklook3` launcher script so QuickLook 3 starts from a shell like ds9.

A macOS `.app` is a directory, and the executable inside it (`Contents/MacOS/QuickLook3`)
is an ordinary command-line program: it parses `sys.argv` and resolves relative paths
against the caller's working directory. The same is true of the Linux one-dir build. All
that is missing for `quicklook3 cube.fits` to work is a name on `PATH`, which is what this module
writes.

The launcher is a two-line `sh` script rather than a symlink or a copy, because a copy of
a PyInstaller binary cannot find its sibling `_internal` directory, and because the script
gives somewhere to put the quarantine check described in `QUARANTINE_HINT`.
"""

import os
import shlex
import stat
import sys
from collections import namedtuple
from pathlib import Path

SHIM_NAME = 'quicklook3'

#: Written into every generated launcher. Its presence is what makes an existing file safe
#: to overwrite on reinstall -- anything without it belongs to someone else.
MARKER = '# Generated by QuickLook 3 (Help -> Install Command Line Tool).'

#: Directories to install into, best first. `/usr/local/bin` is on the default macOS and
#: Linux login PATH; `~/.local/bin` usually is not, but needs no administrator rights.
CANDIDATE_DIRS = ('/usr/local/bin', '~/.local/bin')

#: Where mounted volumes -- including a double-clicked .dmg -- show up.
MOUNT_ROOTS = ('/Volumes', '/media', '/mnt', '/run/media')

#: Directories that are on the default login PATH even when this process cannot see them.
#: An app launched from Finder inherits a minimal environment, so `os.environ['PATH']`
#: is not evidence about the user's shell.
DEFAULT_PATH_DIRS = ('/usr/local/bin', '/usr/bin', '/bin', '/usr/sbin', '/sbin')


class CliInstallError(RuntimeError):
    """Raised for every condition the user has to fix, with the fix in the message."""


def macos_app_bundle(executable=None):
    """The `.app` directory holding `executable`, or None when it is not in a bundle."""
    exe = Path(executable or sys.executable).resolve()
    for parent in exe.parents:
        if parent.suffix == '.app':
            return parent
    return None


def on_read_only_filesystem(path):
    """True when `path` lives on a read-only mount, as a mounted .dmg does."""
    try:
        return bool(os.statvfs(path).f_flag & os.ST_RDONLY)
    except (OSError, AttributeError, ValueError):
        return False


def under_removable_mount(path):
    """True when `path` is inside a directory that mounted volumes appear under."""
    resolved = Path(path).expanduser()
    return any(str(resolved).startswith(root + os.sep) for root in MOUNT_ROOTS)


def on_temporary_volume(path):
    """True when `path` is somewhere a launcher must not point at.

    Both conditions are required. Read-only alone is not enough: since Big Sur the macOS
    system volume is sealed, so `/bin`, `/usr/bin` and everything else shipped with the OS
    reports read-only while being perfectly permanent. A mount root alone is not enough
    either -- `/Volumes` holds ordinary external disks, and on macOS even the boot data
    volume appears there. A read-only volume under a mount root is a disk image.
    """
    return on_read_only_filesystem(path) and under_removable_mount(path)


def launch_command():
    """The argv prefix that starts *this* installation of QuickLook 3.

    Frozen builds are their own launcher. From a source checkout, the interpreter plus
    `main.py` is used, so the generated script keeps working without `uv`.

    `sys.executable` is used as-is rather than resolved: a virtual environment's `python`
    is a symlink to the base interpreter, and following it produces a launcher that runs
    an interpreter with none of the project's dependencies on its path.
    """
    interpreter = os.path.abspath(sys.executable)

    if getattr(sys, 'frozen', False):
        return [interpreter]

    main_py = Path(__file__).resolve().parents[2] / 'main.py'
    if main_py.is_file():
        return [interpreter, str(main_py)]

    raise CliInstallError(
        "Cannot tell how this copy of QuickLook 3 was started. Install the command from a "
        "downloaded application bundle, or from a source checkout containing main.py.")


def shim_text(command, app_bundle=None, name=SHIM_NAME):
    """The launcher script: run `command`, forwarding every argument."""
    quoted = ' '.join(shlex.quote(part) for part in command)
    lines = ['#!/bin/sh', MARKER, '']

    if app_bundle is not None:
        # A bundle downloaded through a browser carries com.apple.quarantine, and macOS
        # kills it with SIGKILL and no output at all when it is run from a shell. Without
        # this check the user sees the command silently do nothing.
        bundle = shlex.quote(str(app_bundle))
        lines += [
            f'APP={bundle}',
            'if xattr -p com.apple.quarantine "$APP" >/dev/null 2>&1; then',
            f'    echo "{name}: macOS has quarantined $APP; it will be killed on launch." >&2',
            f'    echo "{name}: run  xattr -cr \\"$APP\\"  or open the app once from Finder '
            '(right-click, Open)." >&2',
            '    exit 1',
            'fi',
            '',
        ]

    lines.append(f'exec {quoted} "$@"')
    return '\n'.join(lines) + '\n'


def looks_on_path(directory):
    """Whether `directory` is likely to be on the user's shell PATH."""
    resolved = Path(directory).expanduser().resolve()
    if str(resolved) in DEFAULT_PATH_DIRS:
        return True
    for entry in os.environ.get('PATH', '').split(os.pathsep):
        if not entry:
            continue
        try:
            if Path(entry).expanduser().resolve() == resolved:
                return True
        except OSError:
            continue
    return False


def path_hint(directory):
    """A shell line the user should add to their profile, or None when unnecessary."""
    if looks_on_path(directory):
        return None
    return f'export PATH="{directory}:$PATH"'


def can_create(path):
    """Whether `path` could be created, judged from its nearest existing ancestor.

    Checking only the immediate parent is not enough: on a fresh macOS account `~/.local`
    does not exist either, so `~/.local/bin` has no parent to inspect and would be
    rejected even though `mkdir -p` would succeed.
    """
    path = Path(path).expanduser()
    for ancestor in (path, *path.parents):
        if ancestor.exists():
            return ancestor.is_dir() and os.access(ancestor, os.W_OK)
    return False


def choose_install_dir():
    """The first candidate directory that can be written to without elevation."""
    for raw in CANDIDATE_DIRS:
        candidate = Path(raw).expanduser()
        if candidate.is_dir() and os.access(candidate, os.W_OK):
            return candidate
        if not candidate.exists() and can_create(candidate):
            return candidate
    raise CliInstallError(
        "No writable directory to install into. Tried " + ", ".join(CANDIDATE_DIRS) + ".")


#: What an install *would* do. `existing` is None, 'ours' or 'foreign'; `hint` is the shell
#: line needed to reach the launcher, or None when the directory is already on PATH.
InstallPlan = namedtuple('InstallPlan', 'path command app_bundle hint existing name')


def plan(dest_dir=None, name=SHIM_NAME):
    """Work out exactly what `install()` would do, without touching the filesystem.

    Every condition that makes installing impossible raises here, so a caller can show the
    user the consequences -- or the reason it cannot proceed -- before anything is written.
    """
    if sys.platform.startswith('win'):
        raise CliInstallError(
            "Installing a shell launcher is only supported on macOS and Linux.")

    command = launch_command()
    target = Path(command[0])
    bundle = macos_app_bundle(target) if sys.platform == 'darwin' else None

    if on_temporary_volume(bundle or target):
        location = bundle or target
        raise CliInstallError(
            f"QuickLook 3 is running from a read-only volume ({location}), which will "
            "disappear when it is ejected. Copy the application to /Applications (or your "
            "home folder) and run this again from the copy.")

    directory = Path(dest_dir).expanduser() if dest_dir else choose_install_dir()
    path = directory / name

    existing = None
    if path.exists():
        existing = 'ours' if MARKER in _read_text(path) else 'foreign'

    return InstallPlan(path, command, bundle, path_hint(directory), existing, name)


def describe_plan(plan_, done=False):
    """Plain-text lines stating what an install will do, for a dialog or a terminal.

    One wording for both front ends, so the confirmation dialog and `--install-cli` cannot
    describe the same operation differently. `done=True` reports it in the past tense, for
    the message shown after the work has happened.
    """
    def row(label, value):
        return f"{label + ':':<13}{value}"

    lines = [
        row('Created' if done else 'Create', plan_.path),
        row('Which runs', shlex.join(plan_.command)),
    ]
    if plan_.existing == 'ours':
        lines.append(row('Replaced' if done else 'Replaces',
                         'the QuickLook 3 launcher already at that path'))
    lines.append("")

    if plan_.hint:
        lines.append(f"{plan_.path.parent} is not on your PATH. First add this line to your "
                     f"shell profile (~/.zshrc or ~/.bashrc) and open a new terminal:")
        lines.append(f"    {plan_.hint}")
        lines.append("")

    lines.append(f"To run it:   {plan_.name} yourfile.fits")
    lines.append(f"To undo it:  rm {plan_.path}")
    return lines


def install(dest_dir=None, name=SHIM_NAME, force=False, plan_=None):
    """Write the launcher script and return its path.

    Pass `plan_` to install exactly what a previous `plan()` described -- that is what the
    confirmation dialog does, so what the user agreed to is what gets written.

    Raises `CliInstallError` with an actionable message for every expected failure: an
    unsupported platform, an application still running from a disk image, no writable
    directory, or a same-named file this module did not create.
    """
    if plan_ is None:
        plan_ = plan(dest_dir, name)

    if plan_.existing == 'foreign' and not force:
        raise CliInstallError(
            f"{plan_.path} already exists and was not created by QuickLook 3; it was left "
            "alone.")

    try:
        plan_.path.parent.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        raise CliInstallError(f"Cannot create {plan_.path.parent}: {exc}") from exc

    try:
        plan_.path.write_text(
            shim_text(plan_.command, app_bundle=plan_.app_bundle, name=plan_.name))
        plan_.path.chmod(
            plan_.path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    except OSError as exc:
        raise CliInstallError(f"Cannot write {plan_.path}: {exc}") from exc

    return plan_.path


def _read_text(path):
    try:
        return path.read_text(errors='replace')
    except OSError:
        return ''
